back/config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
  }
  resource :profile, only: %i[show edit update]
  # resolve('Profile') { [:profile] }
  resources :movies, only: %i[index show] do
    collection do
      get 'random'
      get 'favorite'
    end
  end
  resources :collections do
    collection do
      get 'my_lists'
      get 'bookmark'
    end
  end
  get 'search', to: 'searches#search'
  resources :favorites, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]

  get "up" => "rails/health#show", as: :rails_health_check

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :api, format: 'json' do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
      controllers: {
        registrations: 'api/v1/auth/registrations',
        sessions: 'api/v1/auth/sessions',
        omniauth_callbacks: 'api/v1/auth/omniauth_callbacks',
      }

      # get 'auth/:provider/callback', to: 'auth/omniauth_callbacks#google_oauth2'
      # post 'auth/:provider/callback', to: 'auth/omniauth_callbacks#google_oauth2'

      resource :profile, only: %i[show edit update]
      resources :movies, only: %i[index show] do
        collection do
          get 'random'
          get 'favorite'
        end
      end
      resources :collections do
        collection do
          get 'my_lists'
          get 'bookmark'
        end
      end
      get 'search', to: 'searches#search'
      resources :favorites, only: %i[create destroy index] do
        delete '', to: 'favorites#destroy', on: :collection
      end

      resources :bookmarks, only: %i[create destroy index] do
        delete '', to: 'bookmarks#destroy', on: :collection
      end
    
      get "up" => "rails/health#show", as: :rails_health_check
    
      if Rails.env.development?
        mount LetterOpenerWeb::Engine, at: "/letter_opener"
      end
    end
  end
end

back/app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigationt">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>    
    <div class="navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

back/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

back/app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-success style="color: red">
    <%= message %>
  </div>
<% end %>

back/app/views/shared/_footer.html.erb
<footer id='footer'>
  <div>
    <div>
      <li class="list-inline-item">
        <%= link_to "利用規約", "#", class: "footer-link" %>
      </li>
      <li class="list-inline-item">
        <%= link_to "お問い合わせ", "#", class: "footer-link" %>
      </li>
      <li class="list-inline-item">
        <%= link_to "プライバシーポリシー", "#", class: "footer-link" %>
      </li>
    </div>
  </div>
</footer>

back/app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigationt">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to "ランダム", movies_path, data: {"turbolinks" => false} %>
          <%= link_to "特集", collections_path %>
          <%= link_to "検索", search_path %>
          <%= link_to "マイページ", profile_path %>
        </li>
      </ul>
    </div>
  </nav>
</header>