back/config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
  }
  resource :profile, only: %i[show edit update]
  # resolve('Profile') { [:profile] }
  resources :movies, only: %i[index show] do
    collection do
      get 'random'
      get 'favorite'
    end
  end
  resources :collections do
    collection do
      get 'my_lists'
      get 'bookmark'
    end
  end
  get 'search', to: 'searches#search'
  resources :favorites, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]

  get "up" => "rails/health#show", as: :rails_health_check

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :api, format: 'json' do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
      controllers: {
        registrations: 'api/v1/auth/registrations',
        sessions: 'api/v1/auth/sessions',
        omniauth_callbacks: 'api/v1/auth/omniauth_callbacks',
      }

      # get 'auth/:provider/callback', to: 'auth/omniauth_callbacks#google_oauth2'
      # post 'auth/:provider/callback', to: 'auth/omniauth_callbacks#google_oauth2'

      resource :profile, only: %i[show edit update]
      resources :movies, only: %i[index show] do
        collection do
          get 'random'
          get 'favorite'
        end
      end
      resources :collections do
        collection do
          get 'my_lists'
          get 'bookmark'
        end
      end
      get 'search', to: 'searches#search'
      resources :favorites, only: %i[create destroy index] do
        delete '', to: 'favorites#destroy', on: :collection
      end

      resources :bookmarks, only: %i[create destroy index] do
        delete '', to: 'bookmarks#destroy', on: :collection
      end
    
      get "up" => "rails/health#show", as: :rails_health_check
    
      if Rails.env.development?
        mount LetterOpenerWeb::Engine, at: "/letter_opener"
      end
    end
  end
end

back/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :movie_id, presence: true
  validates :user_id, presence: true
  validates :user_id, uniqueness: { scope: :movie_id, message: "You have already favorited this movie" }
end

back/app/controllers/api/v1/favorites_controller.rb
module Api
  module V1
    class FavoritesController < ApiController
      include FavoritableMethods

      def index
        items_per_page = params[:per] || 18
        @movies = current_user.favorite_movies.page(params[:page]).per(items_per_page)
  
        if @movies
          render json: { movies: @movies, total_pages: @movies.total_pages }, status: :ok
        else
          render json: { message: 'Favorite not found' }, status: :not_found
        end
      end

      def create
        @movie = Movie.find(params[:movie_id])
        @favorite = current_user.favorites.build(movie: @movie)
        if @favorite.save
          render json: { message: 'Favorited successfully' }, status: :created
        else
          render json: { errors: @favorite.errors.full_messages }, status: :unprocessable_entity
        end
      end
    
      def destroy
        @favorite = current_user.favorites.find_by(movie_id: params[:id])
        if @favorite&.destroy
          render json: { message: 'Unfavorited successfully' }, status: :ok
        else
          render json: { error: 'Favorite not found' }, status: :not_found
        end
      end    
    end
  end
end

back/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    current_user.favorite(@movie)
  end

  def destroy
    @movie = current_user.favorites.find(params[:id]).movie
    current_user.unfavorite(@movie)
  end
end

back/app/helpers/favorites_helper.rb
module FavoritesHelper
end

back/app/views/favorites/_favorite.html.erb
<%= link_to favorites_path(movie_id: movie.id), id: "favorite-button-for-movie-#{movie.id}", data: { turbo_method: :post } do %>
  <i class="fas fa-heart">お気に入りに登録する</i>
<% end %>

back/app/views/favorites/_favorite_button.html.erb
<% if current_user.favorite?(movie) %>
  <%= render "favorites/unfavorite", movie: movie %>
<% else %>
  <%= render "favorites/favorite", movie: movie %>
<% end %>

back/app/views/favorites/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find { |b| b.user_id == current_user.id }),
  id: "unfavorite-button-for-movie-#{movie.id}",
  data: { turbo_method: :delete }, class: "unfavorite-button" do %>
  <i class="fas fa-heart">お気に入りを解除する</i>
<% end %>

back/app/views/favorites/create.turbo_stream.erb
<%= turbo_stream.replace "favorite-button-for-movie-#{@movie.id}" do %>
  <%= render 'favorites/unfavorite', movie: @movie %>
<% end %>

back/app/views/favorites/destroy.turbo_stream.erb
<%= turbo_stream.replace "unfavorite-button-for-movie-#{@movie.id}" do %>
  <%= render 'favorites/favorite', movie: @movie %>
<% end %>