back/config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
  }
  resource :profile, only: %i[show edit update]
  # resolve('Profile') { [:profile] }
  resources :movies, only: %i[index show] do
    collection do
      get 'random'
      get 'favorite'
    end
  end
  resources :collections do
    collection do
      get 'my_lists'
      get 'bookmark'
    end
  end
  get 'search', to: 'searches#search'
  resources :favorites, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]

  get "up" => "rails/health#show", as: :rails_health_check

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :api, format: 'json' do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
      controllers: {
        registrations: 'api/v1/auth/registrations',
        sessions: 'api/v1/auth/sessions',
        omniauth_callbacks: 'api/v1/auth/omniauth_callbacks',
      }

      # get 'auth/:provider/callback', to: 'auth/omniauth_callbacks#google_oauth2'
      # post 'auth/:provider/callback', to: 'auth/omniauth_callbacks#google_oauth2'

      resource :profile, only: %i[show edit update]
      resources :movies, only: %i[index show] do
        collection do
          get 'random'
          get 'favorite'
        end
      end
      resources :collections do
        collection do
          get 'my_lists'
          get 'bookmark'
        end
      end
      get 'search', to: 'searches#search'
      resources :favorites, only: %i[create destroy index] do
        delete '', to: 'favorites#destroy', on: :collection
      end

      resources :bookmarks, only: %i[create destroy index] do
        delete '', to: 'bookmarks#destroy', on: :collection
      end
    
      get "up" => "rails/health#show", as: :rails_health_check
    
      if Rails.env.development?
        mount LetterOpenerWeb::Engine, at: "/letter_opener"
      end
    end
  end
end

back/app/controllers/api/v1/profiles_controller.rb
module Api
  module V1
    class ProfilesController < ApiController
      def show
        @movies = current_user.favorite_movies
        @collections = current_user.bookmark_collections

        Rails.logger.debug(current_user)
  
        render json: { user: current_user, movies: @movies, collections: @collections }
      end
  
      def edit
        @user = User.find(current_user.id)
        render json: { user: @user }
      end
  
      def update
        @user = User.find(current_user.id)
        if @user.update(user_params)
          render json: @user
        else
          render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
        end
      rescue ActiveRecord::RecordInvalid => e
        render json: { status: 'error', message: e.message }, status: :unprocessable_entity
      end
  
      private
  
      def user_params
        params.require(:profile).permit(:name, :email, :avatar)
      end
    end
  end
end

back/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @movies = current_user.favorite_movies
    @collections = current_user.bookmark_collections
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.flash_message.updated', item: User.model_name.human)
    else
      flash.now[:danger] = t('defaults.flash_message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

back/app/helpers/profiles_helper.rb
module ProfilesHelper
end

back/app/views/profiles/edit.html.erb
<div class="center-form">
      <h1>プロフィール編集</h1>  
      <%= form_with model: @user, url: profile_path, local: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %> 
        </div>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="field">
          <%= f.label :avatar,class: "form_label" %>
          <%= f.file_field :avatar, class: "form-control" %>
          <%= f.hidden_field :avatar_cache %>
        </div>
        <%= f.submit "更新", class: 'btn btn-primary' %>
      <% end %>
</div>

back/app/views/profiles/show.html.erb
<div class="profile-container">
  <div class="float-left mb-3">
    <%= image_tag current_user.avatar_url, class: 'rounded-circle', size: '200x200' %>
    <div class="profile-leftside"><%= "#{current_user.name}" %>
      <div>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-delete' %>
        <%= link_to '編集', edit_profile_path, class: 'btn btn-edit' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="link-container">
        <div><%= link_to '自分の特集一覧へ', my_lists_collections_path %></div>
        <div><%= link_to 'ブックマーク一覧へ', bookmark_collections_path %></div>
      </div>
      <div class="favorites-section">
        <div>お気に入り一覧</div>
        <div class="movie-profile-container pt-3">
          <div class="show-collection-movies-container">
            <% @movies.each do |movie| %>
              <%= link_to movie_path(movie.tmdb_id), class: "show-collection-movie-item" do %>
                <%= image_tag("https://image.tmdb.org/t/p/w200#{movie['poster_path']}", alt: movie.original_title, class: 'show-collection-movie-image') %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>